----- Tables ------

CREATE TABLE PRODUCT (
    PRODUCT_ID INT NOT NULL PRIMARY KEY,
    PRODUCT_NAME VARCHAR2(30),
    PACKAGE_ID NUMBER(10),
    CURRENT_INVENTORY_COUNT NUMBER(5),
    STORE_COST NUMBER(10, 2),
    SALE_PRICE NUMBER(10, 2),
    LAST_UPDATE_DATE DATE,
    UPDATED_BY_USER VARCHAR2(30),
    PET_FLAG VARCHAR2(1)
);

CREATE TABLE CUSTOMER (
    CUST_ID INT NOT NULL PRIMARY KEY,
    FIRSTNAME VARCHAR2(20),
    LASTNAME VARCHAR2(25),
    ADDRESS VARCHAR2(32),
    CITY VARCHAR2(20),
    STATE VARCHAR2(2),
    ZIP VARCHAR2(9)
);

CREATE TABLE CUSTOMER_SALE (
    SALES_ID INT NOT NULL PRIMARY KEY,
    CUST_ID NUMBER(10),
    TOTAL_ITEM_AMOUNT NUMBER(10, 2),
    TAX_AMOUNT NUMBER(10, 2),
    TOTAL_SALE_AMOUNT NUMBER(10, 2),
    SALES_DATE DATE,
    SHIPPING_HANDLING_FEE NUMBER(5, 2)
);

CREATE TABLE SALES_ITEM (
    SALES_ID INT NOT NULL PRIMARY KEY,
    SALE_AMOUNT NUMBER(10, 2)
);

CREATE TABLE PET_CARE_LOG (
    PRODUCT_ID INT NOT NULL PRIMARY KEY,
    CREATED_BY_USER VARCHAR2(30),
    LOG_TEXT VARCHAR2(500),
    LAST_UPDATE_DATETIME DATE
);

----- Triggers ---------

-- 1. TRIGGER FOR AUDITING BEFORE INSERT
CREATE OR REPLACE TRIGGER FIRE_BEFORE_INSERTING
BEFORE INSERT ON PET_CARE_LOG
FOR EACH ROW
BEGIN
    :NEW.LAST_UPDATE_DATETIME := SYSDATE;
    :NEW.CREATED_BY_USER := USER;
EXCEPTION
    WHEN OTHERS THEN
        RAISE_APPLICATION_ERROR(-20001, 'AN ERROR OCCURRED WHILE UPDATING AUDIT COLUMNS: ' || SQLERRM);
END;
/

-- 2. TRIGGER FOR VALIDATION BEFORE UPDATE
CREATE OR REPLACE TRIGGER FIRE_BEFORE_UPDATING
BEFORE UPDATE ON PET_CARE_LOG
FOR EACH ROW
BEGIN
    IF :OLD.CREATED_BY_USER != USER THEN
        RAISE_APPLICATION_ERROR(-20002, 'ACCESS DENIED: ONLY ' || :OLD.CREATED_BY_USER || ' CAN MODIFY THIS RECORD.');
    END IF;
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE = -20002 THEN
            RAISE;
        ELSE
            RAISE_APPLICATION_ERROR(-20001, 'AN ERROR OCCURRED DURING UPDATE VALIDATION: ' || SQLERRM);
        END IF;
END;
/

-- 3. TRIGGER FOR PERMISSIONS BEFORE DELETE
CREATE OR REPLACE TRIGGER FIRE_BEFORE_DELETING
BEFORE DELETE ON PET_CARE_LOG
FOR EACH ROW
BEGIN
    IF USER != 'JOEMANAGER' THEN
        RAISE_APPLICATION_ERROR(-20003, 'UNAUTHORIZED: ONLY JOEMANAGER HAS PERMISSION TO DELETE LOGS.');
    END IF;
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE = -20003 THEN
            RAISE;
        ELSE
            RAISE_APPLICATION_ERROR(-20001, 'AN ERROR OCCURRED DURING THE DELETE OPERATION: ' || SQLERRM);
        END IF;
END;
/